"""add_is_superuser_to_users

Revision ID: 2afcaf75f8d2
Revises: a99f551429f1
Create Date: 2026-06-17 00:10:47.789986
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2afcaf75f8d2'
down_revision: Union[str, None] = 'a99f551429f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
